import type { CompanyRecord, DealRecord, OptionPositionRecord } from "./store-types";

export const SEED_COMPANIES: CompanyRecord[] = [
  {
    id: 1,
    name: "Martinez Landscaping & Tree Service",
    company_type: "landscaping",
    contact_name: "Carlos Martinez",
    contact_email: "carlos@martinezlandscaping.com",
    contact_phone: "512-555-0147",
    address_state: "TX",
    padd_region: "R30",
    fleet_size: 8,
    vehicle_types: '["pickup_truck","mower_trailer"]',
    fuel_type: "gasoline",
    monthly_gallons_gasoline: 1800,
    monthly_gallons_diesel: 0,
    annual_revenue: 850000,
    notes:
      "Family-owned since 2008. 8 crews running daily across Austin metro. Fuel costs spiked 35% last year and ate into margins. Looking for ways to stabilize fuel budget for next fiscal year. Currently has no fuel management strategy.",
    status: "active",
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2026-01-20T14:30:00Z",
  },
  {
    id: 2,
    name: "Great Plains Freight LLC",
    company_type: "trucking_local",
    contact_name: "Sarah Johnson",
    contact_email: "sjohnson@gpfreight.com",
    contact_phone: "316-555-0289",
    address_state: "KS",
    padd_region: "R20",
    fleet_size: 12,
    vehicle_types: '["semi","flatbed","box_truck"]',
    fuel_type: "diesel",
    monthly_gallons_gasoline: 0,
    monthly_gallons_diesel: 24000,
    annual_revenue: 3200000,
    notes:
      "Regional freight carrier covering KS, MO, OK, NE. Diesel is 32% of revenue. Lost a major bid last quarter because fuel cost estimates were too uncertain. Needs predictable fuel costs to bid competitively on contracts.",
    status: "active",
    created_at: "2025-10-01T08:00:00Z",
    updated_at: "2026-02-10T09:15:00Z",
  },
  {
    id: 3,
    name: "Bay Area Express Delivery",
    company_type: "delivery",
    contact_name: "Mike Chen",
    contact_email: "mike@bayareaexpress.com",
    contact_phone: "415-555-0193",
    address_state: "CA",
    padd_region: "R50",
    fleet_size: 25,
    vehicle_types: '["van","pickup_truck"]',
    fuel_type: "gasoline",
    monthly_gallons_gasoline: 8750,
    monthly_gallons_diesel: 0,
    annual_revenue: 4500000,
    notes:
      "Last-mile delivery service in SF Bay Area. West Coast gas prices are consistently the highest in the country. 25 vans averaging 350 gal/month each. Exploring hedging to protect margins as they scale to 40 vehicles by Q4.",
    status: "active",
    created_at: "2025-12-05T11:00:00Z",
    updated_at: "2026-03-01T16:45:00Z",
  },
];

export const SEED_DEALS: DealRecord[] = [
  {
    id: 1,
    company_id: 2,
    hedging_plan_id: null,
    fee_structure: "aum_percentage",
    fee_amount: 1.5,
    aum_value: 120000,
    annual_fee_revenue: 1800,
    status: "active",
    signed_date: "2026-01-15",
    notes: "50% hedge on diesel via USO",
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-15T14:00:00Z",
  },
  {
    id: 2,
    company_id: 1,
    hedging_plan_id: null,
    fee_structure: "flat",
    fee_amount: 1000,
    aum_value: null,
    annual_fee_revenue: 1000,
    status: "signed",
    signed_date: "2026-02-20",
    notes: "Conservative 25% hedge plan",
    created_at: "2026-02-15T09:00:00Z",
    updated_at: "2026-02-20T11:00:00Z",
  },
  {
    id: 3,
    company_id: 3,
    hedging_plan_id: null,
    fee_structure: "subscription",
    fee_amount: 350,
    aum_value: null,
    annual_fee_revenue: 4200,
    status: "proposed",
    signed_date: null,
    notes: "Monthly monitoring + quarterly rebalancing",
    created_at: "2026-03-10T13:00:00Z",
    updated_at: "2026-03-10T13:00:00Z",
  },
];

// Demo option positions — calibrated to current ETF price levels (UGA ~$120, USO ~$140 mid-2026)
// so the live tracker shows realistic mid-trade P&L for a sales demo.
export const SEED_OPTION_POSITIONS: OptionPositionRecord[] = [
  {
    id: 1,
    deal_id: 1,
    company_id: 2,
    strategy_key: "long_call",
    ticker: "USO",
    option_type: "call",
    side: "long",
    strike: 140.0,
    expiry: "2026-08-21",
    contracts: 25,
    entry_premium_per_share: 4.5,
    entry_underlying_price: 135.0,
    opened_at: "2026-03-12T10:30:00Z",
    status: "open",
    exit_premium_per_share: null,
    exit_underlying_price: null,
    closed_at: null,
    iv_used: 0.32,
    notes: "100-day ATM call — primary diesel cost protection for Great Plains Freight Q3 fuel exposure",
    created_at: "2026-03-12T10:30:00Z",
    updated_at: "2026-03-12T10:30:00Z",
  },
  {
    id: 2,
    deal_id: 2,
    company_id: 1,
    strategy_key: "long_call",
    ticker: "UGA",
    option_type: "call",
    side: "long",
    strike: 120.0,
    expiry: "2026-09-18",
    contracts: 8,
    entry_premium_per_share: 4.8,
    entry_underlying_price: 116.5,
    opened_at: "2026-03-05T14:15:00Z",
    status: "open",
    exit_premium_per_share: null,
    exit_underlying_price: null,
    closed_at: null,
    iv_used: 0.35,
    notes: "Gasoline hedge for Martinez Landscaping summer peak season",
    created_at: "2026-03-05T14:15:00Z",
    updated_at: "2026-03-05T14:15:00Z",
  },
  {
    id: 3,
    deal_id: 1,
    company_id: 2,
    strategy_key: "covered_call",
    ticker: "USO",
    option_type: "call",
    side: "short",
    strike: 155.0,
    expiry: "2026-06-20",
    contracts: 15,
    entry_premium_per_share: 1.85,
    entry_underlying_price: 142.0,
    opened_at: "2026-04-08T09:45:00Z",
    status: "open",
    exit_premium_per_share: null,
    exit_underlying_price: null,
    closed_at: null,
    iv_used: 0.32,
    notes: "Covered call overlay on 1,500 USO shares — supplemental income, capped at $155",
    created_at: "2026-04-08T09:45:00Z",
    updated_at: "2026-04-08T09:45:00Z",
  },
  {
    id: 4,
    deal_id: 1,
    company_id: 2,
    strategy_key: "collar",
    ticker: "USO",
    option_type: "put",
    side: "long",
    strike: 135.0,
    expiry: "2026-07-17",
    contracts: 15,
    entry_premium_per_share: 1.4,
    entry_underlying_price: 141.0,
    opened_at: "2026-04-15T11:00:00Z",
    status: "open",
    exit_premium_per_share: null,
    exit_underlying_price: null,
    closed_at: null,
    iv_used: 0.32,
    notes: "Floor leg of a collar — $135 put protects against downside",
    created_at: "2026-04-15T11:00:00Z",
    updated_at: "2026-04-15T11:00:00Z",
  },
  {
    id: 5,
    deal_id: 1,
    company_id: 2,
    strategy_key: "collar",
    ticker: "USO",
    option_type: "call",
    side: "short",
    strike: 150.0,
    expiry: "2026-07-17",
    contracts: 15,
    entry_premium_per_share: 1.95,
    entry_underlying_price: 141.0,
    opened_at: "2026-04-15T11:00:00Z",
    status: "open",
    exit_premium_per_share: null,
    exit_underlying_price: null,
    closed_at: null,
    iv_used: 0.32,
    notes: "Ceiling leg of a collar — short $150 call finances the put",
    created_at: "2026-04-15T11:00:00Z",
    updated_at: "2026-04-15T11:00:00Z",
  },
];
